#!/bin/bash
# file name preinst

echo "Pre Installation code here ..."


function createFolderIfNotExists   {
    if [ ! -d $1 ]; then
        mkdir -p $1
    fi
}

function checkifDirectoryIsEmpty {
    if [ -z "$(ls -A $1)" ]; then
        echo "The directory $1 is empty"
        cp /usr/share/multish/files/example $1/example
    else
        echo "The directory $1 is not empty. No Action"
    fi
}

function  checkIfFileExists {
    if [ -f "$1" ]; then
        echo "$1 already exists. No action"
    else
        cp /usr/share/multish/files/.env.example $1
        echo "$1 has been created."
    fi

}

DOTENVFILE="/etc/multish/.env"
checkIfFileExists $DOTENVFILE

FOLDER="/etc/multish/group"
createFolderIfNotExists $FOLDER
checkifDirectoryIsEmpty $FOLDER

ETCFOLDER="/etc/multish"
# Set permissions to 766
chmod -R 766 $ETCFOLDER